/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestVariable } from './restVariable';
import { UserRepresentation } from './userRepresentation';


export interface CaseInstanceRepresentation { 
    id?: string;
    name?: string;
    businessKey?: string;
    caseDefinitionId?: string;
    tenantId?: string;
    started?: string;
    ended?: string;
    startedBy?: UserRepresentation;
    caseDefinitionName?: string;
    caseDefinitionDescription?: string;
    caseDefinitionKey?: string;
    caseDefinitionCategory?: string;
    caseDefinitionVersion?: number;
    caseDefinitionDeploymentId?: string;
    graphicalNotationDefined?: boolean;
    startFormDefined?: boolean;
    variables?: Array<RestVariable>;
}

