/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormContainer } from './formContainer';
import { Option } from './option';
import { ExpressionFormField } from './expressionFormField';
import { LayoutDefinition } from './layoutDefinition';
import { OptionFormField } from './optionFormField';
import { FormField } from './formField';


/**
 * @type FormModelRepresentationFieldsInner
 * @export
 */
export type FormModelRepresentationFieldsInner = ExpressionFormField | FormContainer | FormField | OptionFormField;

