/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LayoutDefinition } from './layoutDefinition';


export interface FormField { 
    id?: string;
    name?: string;
    type?: string;
    value?: object;
    required?: boolean;
    readOnly?: boolean;
    overrideId?: boolean;
    placeholder?: string;
    params?: { [key: string]: object; };
    layout?: LayoutDefinition;
    fieldType: string;
}

