/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRepresentation } from './userRepresentation';


export interface TaskRepresentation { 
    id?: string;
    name?: string;
    description?: string;
    category?: string;
    assignee?: UserRepresentation;
    created?: string;
    dueDate?: string;
    endDate?: string;
    duration?: number;
    priority?: number;
    processInstanceId?: string;
    processInstanceName?: string;
    processDefinitionId?: string;
    processDefinitionName?: string;
    processDefinitionDescription?: string;
    processDefinitionKey?: string;
    processDefinitionCategory?: string;
    processDefinitionVersion?: number;
    processDefinitionDeploymentId?: string;
    scopeId?: string;
    scopeType?: string;
    caseInstanceName?: string;
    scopeDefinitionId?: string;
    caseDefinitionName?: string;
    caseDefinitionDescription?: string;
    caseDefinitionKey?: string;
    caseDefinitionCategory?: string;
    caseDefinitionVersion?: number;
    caseDefinitionDeploymentId?: string;
    parentTaskId?: string;
    parentTaskName?: string;
    formKey?: string;
    processInstanceStartUserId?: string;
    initiatorCanCompleteTask?: boolean;
    involvedPeople?: Array<UserRepresentation>;
    memberOfCandidateGroup?: boolean;
    memberOfCandidateUsers?: boolean;
}

