/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRepresentation } from './groupRepresentation';


export interface UserRepresentation { 
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    fullName?: string;
    tenantId?: string;
    groups?: Array<GroupRepresentation>;
    privileges?: Array<string>;
}

