export * from './appDefinitionsResource.service';
import { AppDefinitionsResourceService } from './appDefinitionsResource.service';
export * from './caseDefinitionResource.service';
import { CaseDefinitionResourceService } from './caseDefinitionResource.service';
export * from './caseDefinitionsResource.service';
import { CaseDefinitionsResourceService } from './caseDefinitionsResource.service';
export * from './caseInstanceDisplayJsonClientResource.service';
import { CaseInstanceDisplayJsonClientResourceService } from './caseInstanceDisplayJsonClientResource.service';
export * from './caseInstanceQueryResource.service';
import { CaseInstanceQueryResourceService } from './caseInstanceQueryResource.service';
export * from './caseInstanceResource.service';
import { CaseInstanceResourceService } from './caseInstanceResource.service';
export * from './caseInstancesResource.service';
import { CaseInstancesResourceService } from './caseInstancesResource.service';
export * from './commentsResource.service';
import { CommentsResourceService } from './commentsResource.service';
export * from './debuggerResource.service';
import { DebuggerResourceService } from './debuggerResource.service';
export * from './hello.service';
import { HelloService } from './hello.service';
export * from './historicTaskQueryResource.service';
import { HistoricTaskQueryResourceService } from './historicTaskQueryResource.service';
export * from './migrateAppDefinitionsResource.service';
import { MigrateAppDefinitionsResourceService } from './migrateAppDefinitionsResource.service';
export * from './processDefinitionResource.service';
import { ProcessDefinitionResourceService } from './processDefinitionResource.service';
export * from './processDefinitionsResource.service';
import { ProcessDefinitionsResourceService } from './processDefinitionsResource.service';
export * from './processInstanceQueryResource.service';
import { ProcessInstanceQueryResourceService } from './processInstanceQueryResource.service';
export * from './processInstanceResource.service';
import { ProcessInstanceResourceService } from './processInstanceResource.service';
export * from './processInstancesResource.service';
import { ProcessInstancesResourceService } from './processInstancesResource.service';
export * from './relatedContentResource.service';
import { RelatedContentResourceService } from './relatedContentResource.service';
export * from './remoteAccountResource.service';
import { RemoteAccountResourceService } from './remoteAccountResource.service';
export * from './runtimeDisplayJsonClientResource.service';
import { RuntimeDisplayJsonClientResourceService } from './runtimeDisplayJsonClientResource.service';
export * from './taskActionResource.service';
import { TaskActionResourceService } from './taskActionResource.service';
export * from './taskFormResource.service';
import { TaskFormResourceService } from './taskFormResource.service';
export * from './taskQueryResource.service';
import { TaskQueryResourceService } from './taskQueryResource.service';
export * from './taskResource.service';
import { TaskResourceService } from './taskResource.service';
export * from './tasksResource.service';
import { TasksResourceService } from './tasksResource.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export * from './workflowGroupResource.service';
import { WorkflowGroupResourceService } from './workflowGroupResource.service';
export * from './workflowGroupsResource.service';
import { WorkflowGroupsResourceService } from './workflowGroupsResource.service';
export * from './workflowUsersResource.service';
import { WorkflowUsersResourceService } from './workflowUsersResource.service';
export const APIS = [AppDefinitionsResourceService, CaseDefinitionResourceService, CaseDefinitionsResourceService, CaseInstanceDisplayJsonClientResourceService, CaseInstanceQueryResourceService, CaseInstanceResourceService, CaseInstancesResourceService, CommentsResourceService, DebuggerResourceService, HelloService, HistoricTaskQueryResourceService, MigrateAppDefinitionsResourceService, ProcessDefinitionResourceService, ProcessDefinitionsResourceService, ProcessInstanceQueryResourceService, ProcessInstanceResourceService, ProcessInstancesResourceService, RelatedContentResourceService, RemoteAccountResourceService, RuntimeDisplayJsonClientResourceService, TaskActionResourceService, TaskFormResourceService, TaskQueryResourceService, TaskResourceService, TasksResourceService, UserResourceService, WorkflowGroupResourceService, WorkflowGroupsResourceService, WorkflowUsersResourceService];
